amcl:
  ros__parameters:
    use_sim_time: true
    
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "/scan"
    
    min_particles: 100
    max_particles: 2000
    
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    
    laser_model_type: "likelihood_field"
    laser_max_range: 10.0
    laser_min_range: 0.1
    max_beams: 60
    z_hit: 0.95
    z_rand: 0.05
    sigma_hit: 0.2
    
    update_min_a: 0.1
    update_min_d: 0.05
    
    resample_interval: 1
    transform_tolerance: 2.0
    
    tf_broadcast: true
    

    always_reset_initial_pose: false
    
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0